[build]
builder = "nixpacks"
buildCommand = "npm install && NITRO_PRESET=node-server npm run build"

[deploy]
startCommand = "node .output/server/index.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
