import json
import random
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

import models
import schemas
import database
from auth_utils import get_current_user

router = APIRouter()


import os
import numpy as np
import joblib

# Determine absolute path to the HealthPredictor files
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(BASE_DIR, "HealthPredictor")

# Load model and encoders once at module level to avoid reloading on each request
try:
    _model = joblib.load(os.path.join(MODEL_DIR, "xgboost_model.pkl"))
    _label_encoder = joblib.load(os.path.join(MODEL_DIR, "label_encoder.pkl"))
    _feature_columns = joblib.load(os.path.join(MODEL_DIR, "feature_columns.pkl"))
except Exception as e:
    print(f"Warning: Could not load ML models. Error: {e}")
    _model, _label_encoder, _feature_columns = None, None, []

def ai_predict(symptoms: List[str]) -> dict:
    """
    Real ML-based predictor using XGBoost.
    """
    if _model is None or _label_encoder is None or not _feature_columns:
        return {
            "disease": "System Error: Model Not Loaded",
            "confidence": 0.0,
            "recommendations": "The AI model is currently unavailable."
        }

    # Clean the internal feature columns to remove leading spaces (e.g. ' sweating' -> 'sweating')
    cleaned_features = [f.strip() for f in _feature_columns]

    # Normalize incoming symptoms (e.g. "Skin Rash" -> "skin_rash")
    input_symptoms = [s.strip().lower().replace(" ", "_") for s in symptoms]
    
    # Create feature vector
    input_data = np.zeros(len(_feature_columns))
    
    for symptom in input_symptoms:
        if symptom in cleaned_features:
            index = cleaned_features.index(symptom)
            input_data[index] = 1
            
    input_data = input_data.reshape(1, -1)
    
    # Predict
    prediction = _model.predict(input_data)
    disease = _label_encoder.inverse_transform(prediction)[0]
    
    # Confidence Score
    probabilities = _model.predict_proba(input_data)
    confidence = round(float(np.max(probabilities)), 2)
    
    return {
        "disease": disease,
        "confidence": confidence,
        "recommendations": (
            "Please consult a qualified healthcare professional for an accurate diagnosis and treatment plan. "
            "This prediction is generated by an AI model based on your symptoms."
        )
    }


# ─────────────────────── Endpoints ───────────────────────

@router.post("/", response_model=schemas.PredictionResponse, status_code=status.HTTP_201_CREATED)
def create_prediction(
    pred_in: schemas.PredictionCreate,
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Run AI prediction on supplied symptoms and save the result."""
    if not pred_in.symptoms:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="At least one symptom is required.",
        )

    result = ai_predict(pred_in.symptoms)

    prediction = models.Prediction(
        user_id=current_user.id,
        symptoms=json.dumps(pred_in.symptoms),
        disease=result["disease"],
        confidence=result["confidence"],
        recommendations=result["recommendations"],
    )
    db.add(prediction)
    db.commit()
    db.refresh(prediction)
    return prediction


@router.get("/history", response_model=List[schemas.PredictionResponse])
def get_history(
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(get_current_user),
    skip: int = 0,
    limit: int = 50,
):
    """Return the prediction history for the currently authenticated user."""
    predictions = (
        db.query(models.Prediction)
        .filter(models.Prediction.user_id == current_user.id)
        .order_by(models.Prediction.created_at.desc())
        .offset(skip)
        .limit(limit)
        .all()
    )
    return predictions


@router.get("/history/{prediction_id}", response_model=schemas.PredictionResponse)
def get_single_prediction(
    prediction_id: int,
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Fetch a single prediction by ID (must belong to the current user)."""
    prediction = (
        db.query(models.Prediction)
        .filter(
            models.Prediction.id == prediction_id,
            models.Prediction.user_id == current_user.id,
        )
        .first()
    )
    if not prediction:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Prediction not found.")
    return prediction


@router.delete("/history/{prediction_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_prediction(
    prediction_id: int,
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Delete a specific prediction from the user's history."""
    prediction = (
        db.query(models.Prediction)
        .filter(
            models.Prediction.id == prediction_id,
            models.Prediction.user_id == current_user.id,
        )
        .first()
    )
    if not prediction:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Prediction not found.")
    db.delete(prediction)
    db.commit()


@router.get("/symptoms", response_model=List[schemas.SymptomResponse])
def list_symptoms(db: Session = Depends(database.get_db)):
    """Return all known symptoms (public — no auth required)."""
    return db.query(models.Symptom).order_by(models.Symptom.name).all()
