/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPredictRouteImport } from './routes/dashboard.predict'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSymptomsRouteImport } from './routes/admin.symptoms'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminPredictionsRouteImport } from './routes/admin.predictions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDiseasesRouteImport } from './routes/admin.diseases'
import { Route as DashboardPredictResultRouteImport } from './routes/dashboard.predict.result'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPredictRoute = DashboardPredictRouteImport.update({
  id: '/dashboard/predict',
  path: '/dashboard/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSymptomsRoute = AdminSymptomsRouteImport.update({
  id: '/admin/symptoms',
  path: '/admin/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/admin/recommendations',
  path: '/admin/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/admin/predictions',
  path: '/admin/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiseasesRoute = AdminDiseasesRouteImport.update({
  id: '/admin/diseases',
  path: '/admin/diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPredictResultRoute = DashboardPredictResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => DashboardPredictRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/symptoms': typeof AdminSymptomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/predict': typeof DashboardPredictRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/predict/result': typeof DashboardPredictResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/symptoms': typeof AdminSymptomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/predict': typeof DashboardPredictRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/predict/result': typeof DashboardPredictResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/symptoms': typeof AdminSymptomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/predict': typeof DashboardPredictRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/predict/result': typeof DashboardPredictResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/diseases'
    | '/admin/login'
    | '/admin/predictions'
    | '/admin/recommendations'
    | '/admin/symptoms'
    | '/admin/users'
    | '/dashboard/history'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/predict/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/diseases'
    | '/admin/login'
    | '/admin/predictions'
    | '/admin/recommendations'
    | '/admin/symptoms'
    | '/admin/users'
    | '/dashboard/history'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/admin'
    | '/dashboard'
    | '/dashboard/predict/result'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/diseases'
    | '/admin/login'
    | '/admin/predictions'
    | '/admin/recommendations'
    | '/admin/symptoms'
    | '/admin/users'
    | '/dashboard/history'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/predict/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminDiseasesRoute: typeof AdminDiseasesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminSymptomsRoute: typeof AdminSymptomsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardPredictRoute: typeof DashboardPredictRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/predict': {
      id: '/dashboard/predict'
      path: '/dashboard/predict'
      fullPath: '/dashboard/predict'
      preLoaderRoute: typeof DashboardPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/symptoms': {
      id: '/admin/symptoms'
      path: '/admin/symptoms'
      fullPath: '/admin/symptoms'
      preLoaderRoute: typeof AdminSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/admin/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diseases': {
      id: '/admin/diseases'
      path: '/admin/diseases'
      fullPath: '/admin/diseases'
      preLoaderRoute: typeof AdminDiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/predict/result': {
      id: '/dashboard/predict/result'
      path: '/result'
      fullPath: '/dashboard/predict/result'
      preLoaderRoute: typeof DashboardPredictResultRouteImport
      parentRoute: typeof DashboardPredictRoute
    }
  }
}

interface DashboardPredictRouteChildren {
  DashboardPredictResultRoute: typeof DashboardPredictResultRoute
}

const DashboardPredictRouteChildren: DashboardPredictRouteChildren = {
  DashboardPredictResultRoute: DashboardPredictResultRoute,
}

const DashboardPredictRouteWithChildren =
  DashboardPredictRoute._addFileChildren(DashboardPredictRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminDiseasesRoute: AdminDiseasesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminSymptomsRoute: AdminSymptomsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardPredictRoute: DashboardPredictRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
